name:                haskell-customer-service
version:             0.1.0.0
github:              "githubuser/haskell-customer-service"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-customer-service#readme>

dependencies:
- base-noprelude >= 4.7 && < 5
- aeson
- classy-prelude
- fmt
- http-types
- postgresql-simple
- postgresql-simple-migration
- resource-pool
- scotty
- wai
- wai-extra

default-extensions:
- OverloadedStrings

library:
  source-dirs: src

executables:
  haskell-customer-service-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    # - -threaded
    - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - haskell-customer-service
    - warp

tests:
  haskell-customer-service-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-customer-service
    - hspec
    - hspec-wai
    - hspec-wai-json
